name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Adjust if you want a different version

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: jamesives/github-pages-deploy-action@v4.6.8  # Use a valid version
        with:
          token: ${{ secrets.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 }}  # Use 'token' instead of 'github_token'
          folder: build  # Use 'folder' instead of 'publish_dir'

