name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Or your default branch
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      

      - name: Set up Git identity
        run: |
          git config --global user.name "Onkar2706"
          git config --global user.email "onkarmahamuni007@gmail.com"

      - name: Install dependencies
        run: npm install
        

      - name: Build project
        run: npm run build
        

      - name: Deploy to GitHub Pages
        run: npm run deploy
        
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}